name = "FirstOrderLogic"
uuid = "1710da80-0bc4-4782-bc8a-9051d75d3351"
authors = ["William Macready <william.macready@gmail.com>"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
